make work

diff --git a/dx/build b/dx/build
--- a/dx/build
+++ b/dx/build
@@ -9,13 +9,24 @@ SCRIPT_DIR=$( cd -- "$( dirname -- "${0}" )" > /dev/null 2>&1 && pwd )
 require_command "docker"
 load_docker_compose_env
 
+
 usage_on_help "Builds the Docker image based on the Dockerfile" "" "build.pre" "build.post" "${@}"
 
-exec_hook_if_exists "build.pre" Dockerfile.dx "${IMAGE}"
+if ! exec_hook_if_exists "build.pre" Dockerfile.dx "${IMAGE}"; then
+  log "build.pre failed"
+  exit 1
+fi
+build_args_file="${SCRIPT_DIR}/build.args"
+BUILD_ARGS=()
+if [ -e "${build_args_file}" ]; then
+  for arg in `grep -v '^#' "${build_args_file}"`; do
+    BUILD_ARGS+=(--build-arg ${arg})
+  done
+fi
 
 docker build \
   --file Dockerfile.dx \
-  --tag "${IMAGE}" \
+  --tag "${IMAGE}" ${BUILD_ARGS[@]} \
   ./
 
 exec_hook_if_exists "build.post" Dockerfile.dx "${IMAGE}"
